version: '3.8'

services:
  web:
    build: 
      context: .
      dockerfile: dockerfile
    image: prueba-backend-image
    ports:
      - "5000:5000"
    environment:
      FLASK_ENV: development
    volumes:
      - .:/app
   